services:
  postgres:
    image: postgres:17
    container_name: auth-api-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: